# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.1.1-26.1
maven_group = net.dialingspoon.partialhearts
archives_name = partialhearts
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.1.2

# Dependencies
fabric_loader_version = 0.19.4
fabric_api_version = 0.155.3+26.1.2
neoforge_version = 26.1.2.109

nightconfig_version = 3.8.4
modmenu_version = 18.0.0-alpha.8

# Compat tests
colorfulhearts_neo = 8240566
colorfulhearts_fabric = 8240567

overflowingbars_neo = 8004645
overflowingbars_fabric = 8004646