# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.1.1-1.21.4
maven_group = net.dialingspoon.partialhearts
archives_name = partialhearts
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.4

# Dependencies
fabric_loader_version = 0.16.10
fabric_api_version = 0.119.4+1.21.4
neoforge_version = 21.4.156

nightconfig_version = 3.8.1
modmenu_version = 13.0.0

# Compat tests
colorfulhearts_neo = 8273223
colorfulhearts_fabric = 8273224

overflowingbars_neo = 6160703
overflowingbars_fabric = 6160700

immediatelyfast_neo = 8348606
immediatelyfast_fabric = 8348604
